jane = {}
jane[:first_name] = "Jane"
jane[:last_name] = "Doe"
jane[:level] = "senior_level"
jane[:age] = 30
jane[:occupation] = "Software Developer"
jane[:employed] = true
jane[:current_salary] = 125,000.00
jane[:languages] = []
jane[:languages] = "Ruby", "JavaScript", "Go"